#
# Makefile to generate python interface code for DSTC
#

CFLAGS += -ggdb
VSD_DIR ?= /usr/local/include


ifndef VSS_SPEC_FILE
${info Please set VSS_SPEC_FILE variable to point to the}
${info vehicle signal specification generated by}
${info https://github.com/GENIVI/vehicle_signal_specification/tree/master/tools/vspec2c}
all:
else
all: vsd_swig_wrap.o
endif

vsd_swig_wrap.o: vsd_swig_wrap.c vss_spec.c
	python3 setup.py build_ext --inplace -I${VSD_DIR}

vsd_swig_wrap.c: vsd_swig.i
	swig -I${VSD_DIR} -python -includeall vsd_swig.i


vss_spec.c: ${VSS_SPEC_FILE}
	cp ${VSS_SPEC_FILE} ./vss_spec.c


${VSS_SPEC_FILE}:

clean:
	rm -rf _vsd*.so build vsd_swig.py vsd_swig_wrap.* __pycache__ \
	dist jlr_vsd.egg-info vss_spec.* *~
